blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ uri42 ê¹ƒí—ˆë¸Œ
    url: https://github.com/kyoulee/uri42
    about: Please ask and answer questions here.
  - name: ğŸŒ ëŒ€íšŒ ì •ë³´
    url: https://www.metaversedev.kr/
    about: ëŒ€íšŒ ë§í¬