name: "ğŸ” ë³´ì•ˆ"
description: "ë³´ì•ˆ ì¶”ê°€ ëŒ€í•œ ë³´ê³ ì„œì…ë‹ˆë‹¤"
title: "ğŸ” "
labels: ["ğŸ” ë³´ì•ˆ"]
projects: []
assignees:
  - kyoulee
body:
  - type: markdown
    attributes:
      value: |
        # ë³´ì•ˆ ì¶”ê°€ ë³´ê³ ì„œ

        ìƒˆë¡œìš´ ë³´ì•ˆì— ëŒ€í•œ ì ìš© ê³¼ì • ë³´ê³ ì„œ ì…ë‹ˆë‹¤.

        ## ë³´ì•ˆ ì‘ì„± ë°©ë²•
          - ë‹¤ìŒì¤„ì— ê¸°ì…ì´ ê°€ëŠ¥í•˜ë©°
          - ê¹ƒ í—ˆë¸Œ ë§ˆí¬ë‹¤ìš´ìœ¼ë¡œ ì‘ë™í•©ë‹ˆë‹¤
  - type: input
    id: input_name
    attributes:
      label: ğŸ“£ ë³´ì•ˆ ì´ë¦„
      description: ğŸ’­ ë³´ì•ˆì˜ ì´ë¦„ì„ ì‘ì„±í•´ ì£¼ì„¸ìš”
      placeholder: ğŸ«§ <ì´ë¦„>
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: ğŸ“£ ë³´ì•ˆ ì¶”ê°€ ì´ìœ 
      description: ğŸ’­ ë³´ì•ˆ ì¶”ê°€í•˜ëŠ” ì´ìœ ì„ ì ì–´ì£¼ì„¸ìš”
      placeholder: |
        ğŸ«§ <ë³´ì•ˆ ìƒì„± ì´ìœ >
        1. <ì´ìœ >
        2. <ì´ìœ >
      render: ''
    validations:
      required: true
  - type: textarea
    id: textarea_work
    attributes:
      label: âœ… ì‘ì—… ë¦¬ìŠ¤íŠ¸
      description: ğŸ’­ ì‘ì—…ì— í•„ìš”í•œ ëª©ë¡ ì‘ì„±
      placeholder: |
        ğŸ«§ <ex. ì˜ˆì‹œ ì§€ë¬¸>
        - [ ] <ì²´í¬ 1>
        - [ ] <ì²´í¬ 2>
      value: |
        - [ ] <ì‘ì—… 1>
        - [ ] <ì‘ì—… 2>
        - [ ] <ì‘ì—… 3>
        - [ ] ë”ì…ë ¥ ...
      render: ''
    validations:
      required: true
  - type: checkboxes
    id: checkboxes_list
    attributes:
      label: ğŸ“£ ì‘ì„±ì ì²´í¬ë¦¬ìŠ¤íŠ¸
      description: ğŸ’­ ì‘ì„±ì ì²´í¬ë¦¬ìŠ¤íŠ¸
      options:
        - label: ğŸ”± ë³´ì•ˆ ì œëª©ì„ ì ì ˆí•˜ê²Œ ì •í•˜ì˜€ìŠµë‹ˆê¹Œ?
          required: false
        - label: ğŸ”± ì‘ì—… ë¦¬ìŠ¤íŠ¸ë¥¼ ì´ìŠˆì— ë§ê²Œ ì„¤ì •í•˜ì…¨ìŠµë‹ˆê¹Œ?
          required: false
        - label: ğŸ“ íƒ€ì´í‹€ì— ë³´ì•ˆ ì´ë¦„ì„ ì¶”ê°€í•˜ì˜€ìŠµë‹ˆê¹Œ?
          required: true
        - label: ğŸ“Œ ì‘ì„±ìëŠ” ëª¨ë“  ì‘ì—…ì— ëŒ€í•œ ì •ë³´ê°€ ê³µê°œë¨ì„ ë™ì˜í•¨ë‹ˆê¹Œ?
          required: true
